export const BUSCAR_ROL = 'BUSCAR_ROL';
export const BUSCAR_ROL_EXITO = 'BUSCAR_ROL_EXITO';
export const BUSCAR_ROL_ERROR = 'BUSCAR_ROL_ERROR';

export const BUSCAR_LISTADO_ROLES = 'BUSCAR_LISTADO_ROLES';
export const BUSCAR_LISTADO_ROLES_EXITO = 'BUSCAR_LISTADO_ROLES_EXITO';
export const BUSCAR_LISTADO_ROLES_ERROR = 'BUSCAR_ROLES_EXITO';

export const CREAR_ROL = 'CREAR_ROL';
export const CREAR_ROL_EXITO = 'CREAR_ROL_EXITO';
export const CREAR_ROL_ERROR = 'CREAR_ROL_ERROR';

export const EDITAR_ROL = 'EDITAR_ROL';
export const EDITAR_ROL_EXITO = 'EDITAR_ROL_EXITO';
export const EDITAR_ROL_ERROR = 'EDITAR_ROL_ERROR';

export const ELIMINAR_ROL = 'ELIMINAR_ROL';
export const ELIMINAR_ROL_EXITO = 'ELIMINAR_ROL_EXITO';
export const ELIMINAR_ROL_ERROR = 'ELIMINAR_ROL_ERROR'; 
