export const BUSCAR_USUARIO = 'BUSCAR_USUARIO';
export const BUSCAR_USUARIO_EXITO = 'BUSCAR_USUARIO_EXITO';
export const BUSCAR_USUARIO_ERROR  = 'BUSCAR_USUARIO_ERROR';

export const BUSCAR_LISTA_USUARIOS = 'BUSCAR_LISTA_USUARIOS';
export const BUSCAR_LISTA_USUARIOS_EXITO = 'BUSCAR_LISTA_USUARIOS_EXITO';
export const BUSCAR_LISTA_USUARIOS_ERROR = 'BUSCAR_LISTA_USUARIOS_ERROR'; 

export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO';
export const REGISTRAR_USUARIO_EXITO = 'REGISTRAR_USUARIO_EXITO';
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR';

export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const EDITAR_USUARIO_EXITO = 'EDITAR_USUARIO_EXITO';
export const EDITAR_USUARIO_ERROR = 'EDITAR_USUARIO_ERROR';

export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const ELIMINAR_USUARIO_EXITO = 'ELIMINAR_USUARIO_EXITO';
export const ELIMINAR_USUARIO_ERROR = 'ELIMINAR_USUARIO_ERROR';

