export const INICIAR_SESSION = 'INICIAR_SESSION';
export const INICIAR_SESSION_EXITO = 'INICIAR_SESSION_EXITO';
export const INICIAR_SESSION_ERROR = 'INICIAR_SESSION_ERROR';

export const CERRAR_SESSION = 'CERRAR_SESSION';

export const VALIDAR_SESSION = 'VALIDAR_SESSION';
export const VALIDAR_SESSION_EXITO = 'VALIDAR_SESSION_EXITO';
export const VALIEDAR_SESSION_ERROR = 'VALIEDAR_SESSION_ERROR';